#' Unit tests for census data functions
#'
#' @details
#' Top-level code should be scoped inside of test_that calls
#'
#'
#' @return
#' @export
#'
#'
#' @importFrom testthat test_that expect_equal
#' @references https://r-pkgs.org/testing-design.html
#'
#' @examples


# add test to check tract and bg fips formatting of areas files downloaded from MCDC

#new test
testthat::test_that("Output dataframe's dimension is as expected",{
  setwd(here::here())

  read_acs_data_output <- read_acs_data()
  testthat::expect_true(read_acs_data_output[1],9129) #9129 rows
  testthat::expect_true(read_acs_data_output[2],72) #72 columns
})

testthat::test_that("All outcomes labeled as being a percentage are actually a percentage",{
  setwd(here::here())

  all_pct_outcomes <- read_acs_data_output %>% select(contains("pct"))
  all_pct_outcomes <- all_pct_outcomes %>% select(!contains("moe"))
  testthat::expect_false(any(all_pct_outcomes > 1, na.rm=TRUE))
})

testthat::test_that("If the percentage of college students in a population is 25%+, poverty estimates are adjusted",{
  #Logic: download census variables again to derive a new poverty estimate that's adjusted for college population
  #       confirm test matches original data
  setwd(here::here())

  moe_level <- 90
  acs_year <- current_year - 3

  pov_variables <- c("B14006_009E","B14006_010E", "B14007_017E", "B14007_018E", "B03002_001E", "C17002_008E", "C17002_001E")
  pov_acs_table_test <- tidycensus::get_acs('tract', year = acs_year, variables = pov_variables, state = '06', output = 'wide', moe_level = moe_level)

  college_pov_ = B14006_009E + B14006_010E
  college_tot_ = B14007_017E + B14007_018E
  total_pop_ = B03002_001E
  above_200_pov_  = C17002_008E
  tot_pop_pov_ = C17002_001E
  prelim_below_pov_ = B17020_002E
  pct_college_ = college_tot_/total_pop_

  below_pov_ = ifelse(pct_college_ < 0.25,
                      prelim_below_pov_,
                      prelim_below_pov_ - college_pov_)
  pct_below_pov_ = below_pov_/tot_pop_pov_

  pct_above_200_pov_  = ifelse(pct_college_ < 0.25,
                               above_200_pov_/tot_pop_pov_,
                               above_200_pov_/(tot_pop_pov_-college_pov_))

  #test that re-derived poverty values are the same as the ones in the dataset generated by the function
  testthat::expect_true(pov_acs_table_test$pct_below_pov_==all_pct_outcomes$pct_below_pov)
  testthat::expect_true(pov_acs_table_test$pct_above_200_pov_==all_pct_outcomes$pct_above_200_pov_)
})

testthat::test_that("All variables that we expect to load are actually loaded, and correctly",{
  setwd(here::here())
  read_acs_data(current_year,'tract',TRUE) #generate a testing file in data-raw/testing, confirm manually
})

