#' Import Neighborhood Change Data
#'
#'
#' @description
#' Imports neighborhood change data generated by CHPC identifying non-rural tracts that
#' have experienced both long-term (since 2000) and recent change (since 2013)
#' racial/ethnic and economic change.
#'
#'
#' @param year designates the map year's filepaths
#'
#'
#' @examples
#' neighborhood_change(year = 2024) # imports neighborhood change output and reduces to necessary variables
#'
#'
#'
#'
#' @author Matt Alvarez-Nissen `mnissen@chpc.net`
#' @export
read_neighborhood_change <- function(year = current_year){
  filepaths(year=year)
  change_all <- read_csv(nc_scores)

  change_cols <- c(
    # pathway 1A
    'baseline_raceinc0021',
    'trct_raceeth_chng0021',
    'raceeth_half0021',
    'trct_inc_chng0021',
    'inc_half0021',
    'part1',
    # pathway 1B
    'baseline_race1321',
    'baseline_income1321',
    'trct_raceeth_chng1321',
    'raceeth_quarter1321',
    'trct_inc_chng1321',
    'inc_quarter1321',
    'part3', # change name below
    # pathway 2
    'halfmile_buffer',
    'raceeth_half1321',
    'inc_half1321',
    'trct_pctchng_medrent1321',
    'rent_half1321',
    'pct_gap',
    'part2',
    # nc flag
    'nbrhood_chng'
  )

  change <- change_all %>%
    dplyr::select('fips' = 'tract2020',
                  all_of(change_cols), exclusion_flag, rural_flag)

  # final prep
  change <- change %>%
    # add flat income gap threshold
    mutate(gap_thresh = .25) %>%
    # apply NA's
    mutate_at(vars(append(change_cols, 'gap_thresh')), ~
                replace(., exclusion_flag == 1, NA)) %>%
    mutate_at(vars(append(change_cols, 'gap_thresh')), ~
                replace(., rural_flag == 1, NA)) %>%
    # rename based on final methodology
    rename(
      'path_1a' = part1,
      'path_1b' = part3,
      'path_2' = part2,
      'nc_exclude_flag' = exclusion_flag) %>%
    # relocate gap field
    relocate(gap_thresh, .after = pct_gap) %>%
    # drop rural flag
    select(-rural_flag)

  return(change)
}
