#' Import Neighborhood Change Data
#'
#'
#' @description
#' Imports neighborhood change data generated by CHPC identifying non-rural tracts that
#' have experienced both long-term (since 2000) and recent change (since 2013)
#' racial/ethnic and economic change.
#'
#'
#' @param year designates the map year's filepaths
#'
#'
#' @examples
#' neighborhood_change(year = 2024) # imports neighborhood change output and reduces to necessary variables
#'
#'
#'
#'
#' @author Matt Alvarez-Nissen `mnissen@chpc.net`
#' @export
read_neighborhood_change <- function(year = current_year){
  filepaths(year=year)
  change_all <- read_csv(nc_scores)


  change <- change_all %>%
    dplyr::select('fips' = 'tract2020',
                  #all_of(change_cols),
                  starts_with('baseline'),
                  starts_with('trct_raceeth'),
                  starts_with('trct_medinc_pctchng'),
                  starts_with('raceeth'),
                  starts_with('medinc'),
                  halfmile_buffer,
                  starts_with('trct_pctchng_medrent'),
                  starts_with('rent'),
                  starts_with('pct_gap'),
                  starts_with('pathway'),
                  starts_with('nbrhood_chng'),
                  'nc_exclusion_flag' = exclusion_flag,
                  rural_flag)

  # final prep
  change <- change %>%
    # add flat income gap threshold
    mutate(gap_thresh = .25) %>%
    # apply null values where exclusion or rural flag is raised
    mutate_at(
      vars(select_if(., is.numeric) %>% names() %>% setdiff(c("nc_exclusion_flag", "rural_flag"))),
      ~ replace(., nc_exclusion_flag == 1 | rural_flag == 1, NA)
    ) %>%
    # relocate gap field
    relocate(gap_thresh, .after = pct_gap) %>%
    # drop rural flag
    select(-rural_flag)

  return(change)
}
