#' Import Neighborhood Change Data
#'
#'
#' @description
#' Imports neighborhood change data generated by CHPC identifying non-rural tracts that
#' have experienced both long-term (since 2000) and recent change (since 2013)
#' racial/ethnic and economic change.
#'
#'
#' @param year designates the map year's filepaths
#'
#'
#' @examples
#' neighborhood_change(year = 2024) # imports neighborhood change output and reduces to necessary variables
#'
#'
#'
#'
#' @author Matt Alvarez-Nissen `mnissen@chpc.net`
#' @export
read_neighborhood_change <- function(year = current_year){
  filepaths(year=year)

  change_all <- read_zip(nc_scores, year, col_types = readr::cols())

  change <- change_all %>%
    dplyr::rename('fips' = tract2020) %>%
    dplyr::select(fips,
                  rural_flag,
                  baseline_raceinc0021,
                  baseline_race1321,
                  part1,
                  part2,
                  nbrhood_chng,
                  trct_raceeth_chng0021,
                  trct_raceeth_chng1321,
                  trct_inc_chng0021,
                  trct_inc_chng1321,
                  halfmile_buffer,
                  raceeth_half0021,
                  raceeth_half1321,
                  inc_half0021,
                  inc_half1321,
                  rent_quarter1321,
                  trct_pctchng_medrent1321
  )

  # insert NA for rural areas
  change <- change %>%
    mutate_at(vars(baseline_raceinc0021:trct_pctchng_medrent1321), ~
                replace(., rural_flag == 1, NA)) %>%
    select(-rural_flag)

  return(change)
}
